
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: nchuOJ-backend-user-service
          uri: lb://nchuOJ-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: nchuOJ-backend-post-service
          uri: lb://nchuOJ-backend-post-service
          predicates:
            - Path=/api/post/**
        - id: nchuOJ-backend-question-service
          uri: lb://nchuOJ-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: nchuOJ-backend-exam-service
          uri: lb://nchuOJ-backend-exam-service
          predicates:
            - Path=/api/exam/**
        - id: nchuOJ-backend-judge-service
          uri: lb://nchuOJ-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: nchuOJ-backend-sendbox-service
          uri: lb://nchuOJ-backend-sendbox-service
          predicates:
            - Path=/api/sendbox/**

  application:
    name: nchuOJ-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8100

knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : swagger2